import React, { useState, useEffect, useRef, useCallback } from "react";
import { sb, SUPABASE_URL, SUPABASE_ANON_KEY, B, F, M, IS, LS, BP, BS, PC, SC, SL, PSC, PSL, ROLES, haptic, cleanText, autoCorrect, sanitizeHTML, calcWOHours, genPO, genProjectPO } from "../shared";
import { Card, Badge, StatCard, Modal, Toast, Spinner, SkeletonLoader, EmptyState, CustomSelect } from "./ui";

function BillingExport({wos,pos,timeEntries,customers,emailTemplates,currentUser}){
  const[toast,setToast]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[custFilter,setCustFilter]=useState("");
  const[showEmail,setShowEmail]=useState(false),[emailTo,setEmailTo]=useState(""),[emailCC,setEmailCC]=useState(""),[sending,setSending]=useState(false);
  const[emailSubject,setEmailSubject]=useState("3C Refrigeration \u2014 Timesheet"),[emailBody,setEmailBody]=useState("<p>Hi,</p><p>Please find attached the timesheet.</p><p>If you have any questions, please reply to this email.</p>");
  const[contacts,setContacts]=useState([]),[suggestions,setSuggestions]=useState([]),[showSugTo,setShowSugTo]=useState(false),[showSugCC,setShowSugCC]=useState(false);
  const applyTemplate=(tpl)=>{if(!tpl){setEmailSubject("3C Refrigeration \u2014 Timesheet");setEmailBody("<p>Hi,</p><p>Please find attached the timesheet.</p><p>If you have any questions, please reply to this email.</p>");return;}setEmailSubject(tpl.subject);setEmailBody(tpl.body);};
  useEffect(()=>{if(custFilter){const c=customers.find(x=>x.name===custFilter);if(c?.email&&!emailTo)setEmailTo(c.email);}},[custFilter]);
  const allCols={wo_id:"WO#",customer_wo:"Customer WO#",date_completed:"Date",customer:"Customer",title:"Title",location:"Location",building:"Building",wo_type:"Type",hours:"Hours",po_total:"PO $",notes:"Job Details",field_notes:"Field Notes"};
  const[cols,setCols]=useState(["wo_id","customer_wo","date_completed","customer","title","location","building","wo_type","hours","po_total"]);
  const presets={basic:["wo_id","customer_wo","date_completed","customer","hours"],detailed:["wo_id","customer_wo","date_completed","customer","title","location","building","hours","po_total"],full:Object.keys(allCols)};
  const[showCustomCols,setShowCustomCols]=useState(false);
  const activePreset=Object.entries(presets).find(([k,v])=>v.length===cols.length&&v.every(c=>cols.includes(c)))?.[0]||"custom";
  const completed=wos.filter(o=>{if(o.status!=="completed")return false;if(custFilter&&o.customer!==custFilter)return false;if(!dateFrom&&!dateTo)return true;const woTime=timeEntries.filter(t=>t.wo_id===o.id);if(woTime.length===0)return(!dateFrom||o.date_completed>=dateFrom)&&(!dateTo||o.date_completed<=dateTo);return woTime.some(t=>{const d=t.logged_date||o.date_completed;return(!dateFrom||d>=dateFrom)&&(!dateTo||d<=dateTo);});});
  const getData=wo=>{const woTime=timeEntries.filter(t=>t.wo_id===wo.id);const filteredTime=woTime.filter(t=>{const d=t.logged_date||wo.date_completed;return(!dateFrom||d>=dateFrom)&&(!dateTo||d<=dateTo);});const h=filteredTime.reduce((s,t)=>s+parseFloat(t.hours||0),0);const p=pos.filter(p=>p.wo_id===wo.id&&p.status==="approved").reduce((s,p)=>s+parseFloat(p.amount||0),0);const cleanNotes=(wo.notes||"").replace(/\n/g," ").trim();const cleanField=(wo.field_notes||"").replace(/\n/g," ").trim();return{wo_id:wo.wo_id,customer_wo:wo.customer_wo||"",date_completed:wo.date_completed||"",customer:wo.customer||"",title:wo.title,location:wo.location||"",building:wo.building||"",wo_type:wo.wo_type||"CM",hours:h,hours_display:h+"h",po_total:"$"+p.toFixed(2),notes:cleanNotes,field_notes:cleanField};};
  // Load saved contacts
  useEffect(()=>{sb().from("email_contacts").select("*").order("last_used",{ascending:false}).then(({data})=>{if(data)setContacts(data);});},[]);
  const saveContact=async(email)=>{if(!email)return;const existing=contacts.find(c=>c.email.toLowerCase()===email.toLowerCase());if(existing){await sb().from("email_contacts").update({last_used:new Date().toISOString()}).eq("id",existing.id);setContacts(prev=>prev.map(c=>c.id===existing.id?{...c,last_used:new Date().toISOString()}:c));}else{const{data}=await sb().from("email_contacts").insert({email:email.toLowerCase()}).select().single();if(data)setContacts(prev=>[data,...prev]);}};
  const filterContacts=(val)=>contacts.filter(c=>c.email.toLowerCase().includes(val.toLowerCase())).slice(0,5);
  const copyToClip=()=>{const header=cols.map(c=>allCols[c]).join("\t")+"\n";const rows=completed.map(wo=>{const d=getData(wo);return cols.map(c=>c==="hours"?d.hours:d[c]).join("\t");}).join("\n");navigator.clipboard.writeText(header+rows).then(()=>{setToast("Copied!");setTimeout(()=>setToast(""),3000);});};
  const earliest=(a,b)=>{if(!a)return b||"";if(!b)return a;return a<b?a:b;};
  const getTimesheetRows=()=>{const rows=[];let totalHrs=0;completed.forEach(wo=>{const woNum=wo.customer_wo||wo.wo_id;const woTime=timeEntries.filter(t=>t.wo_id===wo.id);if(woTime.length>0){const filtered=woTime.filter(t=>{const d=t.logged_date||wo.date_completed;return(!dateFrom||d>=dateFrom)&&(!dateTo||d<=dateTo);});filtered.forEach(te=>{const h=parseFloat(te.hours||0);rows.push({date:te.logged_date||wo.date_completed||"",building:wo.building||"",room:wo.location||"",wo_num:woNum,hours:h,desc:te.description||wo.title,tech:te.technician||""});totalHrs+=h;});}else{rows.push({date:wo.date_completed||"",building:wo.building||"",room:wo.location||"",wo_num:woNum,hours:0,desc:wo.title,tech:""});}}); rows.sort((a,b)=>(a.date||"").localeCompare(b.date||""));return{rows,totalHrs};};
  const buildTimesheetXLSX=async()=>{
    const ExcelJS=await import("exceljs");
    const{rows,totalHrs}=getTimesheetRows();
    const wb=new ExcelJS.default.Workbook();wb.creator="3C FieldOps Pro";
    const sheetName=((custFilter||"Timesheet")+(dateFrom?" "+dateFrom:"")+(dateTo?" to "+dateTo:"")).slice(0,31);
    const ws=wb.addWorksheet(sheetName);
    ws.columns=[{width:14},{width:14},{width:12},{width:16},{width:14},{width:40}];
    const thinBorder={style:"thin",color:{argb:"FFDDDDDD"}};
    const headerFill={type:"pattern",pattern:"solid",fgColor:{argb:"FF00B7E8"}};
    const totalFill={type:"pattern",pattern:"solid",fgColor:{argb:"FFE8F5E9"}};
    // Header row
    const hdr=ws.addRow(["Date:","Building #","Room#","WO/Asset#","Personnel Hrs.","Description"]);
    hdr.height=22;hdr.eachCell(c=>{c.font={name:"Calibri",size:13,bold:true,color:{argb:"FFFFFFFF"}};c.fill=headerFill;c.alignment={horizontal:"center",vertical:"middle"};c.border={top:{style:"medium"},bottom:{style:"medium"}};});
    // Data rows
    rows.forEach(r=>{const row=ws.addRow([r.date,r.building,r.room,r.wo_num,r.hours,r.desc||""]);
      row.eachCell((c,i)=>{c.font={name:"Calibri",size:11,bold:i===5};c.border={bottom:thinBorder};});
      row.getCell(5).numFmt="0.00";});
    // Total row
    const totRow=ws.addRow(["","","","TOTAL:",totalHrs,""]);
    totRow.getCell(4).font={name:"Calibri",size:12,bold:true};totRow.getCell(4).fill=totalFill;
    totRow.getCell(5).font={name:"Calibri",size:12,bold:true};totRow.getCell(5).fill=totalFill;totRow.getCell(5).numFmt="0.00";
    return wb;
  };
  const buildXLSXBase64=async()=>{const wb=await buildTimesheetXLSX();const buf=await wb.xlsx.writeBuffer();return btoa(String.fromCharCode(...new Uint8Array(buf)));};
  const generateXLSX=async()=>{
    try{const wb=await buildTimesheetXLSX();const buf=await wb.xlsx.writeBuffer();
      const blob=new Blob([buf],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
      const url=URL.createObjectURL(blob);const a=document.createElement("a");
      a.href=url;a.download="3C_Timesheet"+(custFilter?"_"+custFilter.replace(/\s/g,"_"):"")+(dateFrom&&dateTo?"_"+dateFrom+"_to_"+dateTo:dateFrom?"_"+dateFrom:"")+".xlsx";
      a.click();URL.revokeObjectURL(url);setToast("Downloaded");setTimeout(()=>setToast(""),3000);
    }catch(e){setToast("Error: "+e.message);console.error(e);}
  };
  const LOGO_URL="https://gwwijjkahwieschfdfbq.supabase.co/storage/v1/object/public/photos/Main%20Logo%20-%20Transparent%20Bg%201.png";
  const buildSig=()=>{const u=currentUser;if(!u)return"";return '<div style="margin-top:20px;padding-top:12px;border-top:1px solid #ddd;font-family:Calibri,sans-serif;font-size:13px;color:#333;"><strong>'+u.name+'</strong><br/>'+(u.title?u.title+'<br/>':'')+(u.phone?u.phone+'<br/>':'')+'<img src="'+LOGO_URL+'" alt="3C Refrigeration" style="width:120px;height:auto;margin-top:6px;display:block;"/></div>';};
  const sendTimesheet=async()=>{if(!emailTo.trim()||sending)return;setSending(true);const fname="3C_Timesheet"+(custFilter?"_"+custFilter.replace(/\s/g,"_"):"")+(dateFrom&&dateTo?"_"+dateFrom+"_to_"+dateTo:dateFrom?"_"+dateFrom:"")+".xlsx";const xlsB64=await buildXLSXBase64();const{rows,totalHrs}=getTimesheetRows();let tbl='<table style="border-collapse:collapse;width:100%;margin:16px 0;"><tr style="background:#00B7E8;color:#fff;">';["Date","Building #","Room#","WO/Asset#","Hrs.","Description"].forEach(c=>{tbl+='<th style="padding:8px 12px;text-align:left;border:1px solid #ddd;">'+c+'</th>';});tbl+='</tr>';rows.forEach((r,i)=>{tbl+='<tr style="background:'+(i%2===0?'#f9f9f9':'#fff')+';"><td style="padding:6px 12px;border:1px solid #ddd;">'+r.date+'</td><td style="padding:6px 12px;border:1px solid #ddd;">'+r.building+'</td><td style="padding:6px 12px;border:1px solid #ddd;">'+r.room+'</td><td style="padding:6px 12px;border:1px solid #ddd;">'+r.wo_num+'</td><td style="padding:6px 12px;border:1px solid #ddd;font-weight:bold;">'+r.hours+'</td><td style="padding:6px 12px;border:1px solid #ddd;">'+r.desc+'</td></tr>';});tbl+='<tr style="background:#E8F5E9;font-weight:bold;"><td colspan="4" style="padding:8px 12px;border:1px solid #ddd;text-align:right;">TOTAL:</td><td style="padding:8px 12px;border:1px solid #ddd;">'+totalHrs.toFixed(1)+'</td><td></td></tr></table>';const fullBody='<div style="font-family:Calibri,sans-serif;">'+emailBody+tbl+buildSig()+'</div>';try{const emails=emailTo.split(",").map(e=>e.trim()).filter(Boolean);for(const em of emails){await saveContact(em);}if(emailCC){emailCC.split(",").map(e=>e.trim()).filter(Boolean).forEach(em=>saveContact(em));}const resp=await fetch(SUPABASE_URL+"/functions/v1/send-email",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+SUPABASE_ANON_KEY},body:JSON.stringify({to:emailTo.trim(),cc:emailCC.trim(),subject:emailSubject+(custFilter?" for "+custFilter:"")+(dateFrom&&dateTo?" ("+dateFrom+" to "+dateTo+")":dateFrom?" ("+dateFrom+")":""),body:fullBody,attachment:{name:fname,content:xlsB64,type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}})});const result=await resp.json();if(result.success){setToast("Email sent!");setShowEmail(false);setEmailTo("");setEmailCC("");sb().from("email_contacts").select("*").order("last_used",{ascending:false}).then(({data})=>{if(data)setContacts(data);});}else{setToast("Error: "+(result.error||"Failed"));console.error(result);}}catch(err){setToast("Error sending");console.error(err);}setSending(false);setTimeout(()=>setToast(""),4000);};
  const SugBox=({items,onPick,show})=>{if(!show||items.length===0)return null;return <div style={{position:"absolute",top:"100%",left:0,right:0,background:B.surface,border:"1px solid "+B.border,borderRadius:6,zIndex:100,maxHeight:150,overflowY:"auto",boxShadow:"0 4px 12px rgba(0,0,0,.4)"}}>{items.map(c=><div key={c.id} onClick={()=>onPick(c.email)} style={{padding:"8px 12px",fontSize:13,color:B.text,cursor:"pointer",borderBottom:"1px solid "+B.border}} onMouseEnter={e=>e.currentTarget.style.background=B.cyanGlow} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>{c.email}</div>)}</div>;};
  return(<div><Toast msg={toast}/>
    <h3 style={{margin:"0 0 14px",fontSize:15,fontWeight:800,color:B.text}}>Customer Billing Export</h3>
    <div style={{display:"flex",gap:10,marginBottom:14,flexWrap:"wrap"}}>
      <div><label style={LS}>From</label><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} style={IS}/></div>
      <div><label style={LS}>To</label><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} style={IS}/></div>
      <div><label style={LS}>Customer</label><select value={custFilter} onChange={e=>setCustFilter(e.target.value)} style={{...IS,cursor:"pointer"}}><option value="">All Customers</option>{(customers||[]).map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div>
    </div>
    <div style={{marginBottom:10}}>
      <span style={LS}>Export Columns</span>
      <div style={{display:"flex",gap:6,marginTop:6}}>
        {[["basic","Basic","WO#, Date, Customer, Hours"],["detailed","Detailed","+ Title, Location, Building, POs"],["full","Full","All columns"]].map(([k,label,desc])=><button key={k} onClick={()=>setCols(presets[k])} style={{flex:1,padding:"10px 8px",borderRadius:6,border:"2px solid "+(activePreset===k?B.cyan:B.border),background:activePreset===k?B.cyanGlow:"transparent",cursor:"pointer",textAlign:"center"}}><div style={{fontSize:12,fontWeight:700,color:activePreset===k?B.cyan:B.text}}>{label}</div><div style={{fontSize:9,color:B.textDim,marginTop:2}}>{desc}</div></button>)}
      </div>
      <button onClick={()=>setShowCustomCols(!showCustomCols)} style={{background:"none",border:"none",color:B.textDim,fontSize:10,cursor:"pointer",marginTop:6,fontFamily:F}}>{showCustomCols?"▾ Hide custom":"▸ Customize columns"}</button>
      {showCustomCols&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:6}}>{Object.entries(allCols).map(([k,v])=><button key={k} onClick={()=>setCols(prev=>prev.includes(k)?prev.filter(c=>c!==k):[...prev,k])} style={{padding:"4px 10px",borderRadius:4,border:"1px solid "+(cols.includes(k)?B.cyan:B.border),background:cols.includes(k)?B.cyanGlow:"transparent",color:cols.includes(k)?B.cyan:B.textDim,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:F}}>{v}</button>)}</div>}
    </div>
    {/* Billing Stats */}
    {(()=>{const totalHrs=completed.reduce((s,wo)=>{const ft=timeEntries.filter(t=>t.wo_id===wo.id).filter(t=>{const d=t.logged_date||wo.date_completed;return(!dateFrom||d>=dateFrom)&&(!dateTo||d<=dateTo);});return s+ft.reduce((ss,t)=>ss+parseFloat(t.hours||0),0);},0);const totalPOs=completed.reduce((s,wo)=>s+pos.filter(p=>p.wo_id===wo.id&&p.status==="approved").reduce((ss,p)=>ss+parseFloat(p.amount||0),0),0);const pendingPOs=completed.reduce((s,wo)=>s+pos.filter(p=>p.wo_id===wo.id&&p.status==="pending").length,0);const avgHrs=completed.length>0?(totalHrs/completed.length).toFixed(1):0;return(<div style={{display:"flex",gap:10,marginBottom:16,flexWrap:"wrap"}}><StatCard label="Work Orders" value={completed.length} icon="📋" color={B.cyan}/><StatCard label="Total Hours" value={totalHrs.toFixed(1)+"h"} icon="⏱" color={B.orange}/><StatCard label="Avg Hrs/WO" value={avgHrs+"h"} icon="📊" color={B.green}/><StatCard label="PO Total" value={"$"+totalPOs.toFixed(2)} icon="💰" color={B.purple}/>{pendingPOs>0&&<StatCard label="Pending POs" value={pendingPOs} icon="⏳" color={B.red}/>}</div>);})()}
    <Card style={{overflowX:"auto",marginBottom:14}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{borderBottom:"2px solid "+B.border}}>{cols.map(c=><th key={c} style={{textAlign:"left",padding:"6px 8px",color:B.textDim,fontWeight:700,fontSize:10,textTransform:"uppercase"}}>{allCols[c]}</th>)}</tr></thead><tbody>{completed.map(wo=>{const d=getData(wo);return(<tr key={wo.id} style={{borderBottom:"1px solid "+B.border}}>{cols.map(c=><td key={c} style={{padding:"6px 8px",fontFamily:c==="wo_id"||c==="hours"||c==="po_total"?M:F,color:c==="wo_id"?B.cyan:c==="hours"?B.cyan:B.text}}>{c==="hours"?d.hours_display:d[c]}</td>)}</tr>);})}</tbody></table></Card>
    <div style={{display:"flex",gap:8}}>
      <button onClick={copyToClip} style={{...BP,flex:1}}>📋 Copy</button>
      <button onClick={generateXLSX} style={{...BP,flex:1,background:B.green}}>📄 Download</button>
      <button onClick={()=>setShowEmail(true)} style={{...BP,flex:1,background:B.purple}}>📧 Email</button>
    </div>
    {showEmail&&<Modal title="Send Timesheet via Email" onClose={()=>setShowEmail(false)} wide>
      <div style={{display:"flex",flexDirection:"column",gap:12}}>
        <div style={{background:B.bg,borderRadius:6,padding:10,border:"1px solid "+B.border,fontSize:12,color:B.textMuted}}>Attaching 3C Timesheet (.xlsx) with {completed.length} entries{custFilter?" for "+custFilter:""} from <span style={{color:B.cyan}}>service@3crefrigeration.com</span></div>
        {(()=>{const warnings=[];const zeroHrs=completed.filter(wo=>{const ft=timeEntries.filter(t=>t.wo_id===wo.id).filter(t=>{const d=t.logged_date||wo.date_completed;return(!dateFrom||d>=dateFrom)&&(!dateTo||d<=dateTo);});return ft.reduce((s,t)=>s+parseFloat(t.hours||0),0)===0;});const noDesc=completed.filter(wo=>!wo.work_performed&&!wo.notes||wo.notes==="No details.");const noDate=completed.filter(wo=>!wo.date_completed);if(zeroHrs.length>0)warnings.push({icon:"⏱",msg:zeroHrs.length+" WO"+(zeroHrs.length>1?"s have":" has")+" 0 hours logged: "+zeroHrs.map(w=>w.wo_id).join(", ")});if(noDesc.length>0)warnings.push({icon:"📝",msg:noDesc.length+" WO"+(noDesc.length>1?"s have":" has")+" no work description: "+noDesc.map(w=>w.wo_id).join(", ")});if(noDate.length>0)warnings.push({icon:"📅",msg:noDate.length+" WO"+(noDate.length>1?"s have":" has")+" no completion date"});return warnings.length>0?<div style={{display:"flex",flexDirection:"column",gap:4}}>{warnings.map((w,i)=><div key={i} style={{background:B.orange+"15",border:"1px solid "+B.orange+"33",borderRadius:6,padding:"8px 12px",fontSize:11,color:B.orange,display:"flex",alignItems:"center",gap:8}}><span>{w.icon}</span><span>{w.msg}</span></div>)}</div>:null;})()}
        <div><label style={LS}>Email Template</label><select onChange={e=>{const t=(emailTemplates||[]).find(x=>x.id===e.target.value);applyTemplate(t);}} style={{...IS,cursor:"pointer"}}><option value="">— Default —</option>{(emailTemplates||[]).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>
        <div style={{position:"relative"}}><label style={LS}>To <span style={{color:B.red}}>*</span></label><input value={emailTo} onChange={e=>{setEmailTo(e.target.value);setSuggestions(filterContacts(e.target.value));setShowSugTo(true);}} onFocus={()=>{setSuggestions(filterContacts(emailTo));setShowSugTo(true);}} onBlur={()=>setTimeout(()=>setShowSugTo(false),200)} placeholder="customer@example.com" style={{...IS,fontSize:14,padding:12}}/><SugBox items={suggestions} show={showSugTo} onPick={e=>{setEmailTo(e);setShowSugTo(false);}}/></div>
        <div style={{position:"relative"}}><label style={LS}>CC <span style={{color:B.textDim,fontWeight:400}}>(optional)</span></label><input value={emailCC} onChange={e=>{setEmailCC(e.target.value);setSuggestions(filterContacts(e.target.value.split(",").pop().trim()));setShowSugCC(true);}} onFocus={()=>{setSuggestions(filterContacts(emailCC.split(",").pop().trim()));setShowSugCC(true);}} onBlur={()=>setTimeout(()=>setShowSugCC(false),200)} placeholder="boss@example.com" style={{...IS,fontSize:14,padding:12}}/><SugBox items={suggestions} show={showSugCC} onPick={e=>{const parts=emailCC.split(",").map(s=>s.trim()).filter(Boolean);parts.pop();parts.push(e);setEmailCC(parts.join(", "));setShowSugCC(false);}}/></div>
        <div><label style={LS}>Subject</label><input value={emailSubject} onChange={e=>setEmailSubject(e.target.value)} style={{...IS,fontSize:14,padding:12}}/></div>
        <div><label style={LS}>Message <span style={{color:B.textDim,fontWeight:400}}>(timesheet table added automatically below)</span></label><textarea value={emailBody} onChange={e=>setEmailBody(e.target.value)} rows={4} style={{...IS,resize:"vertical",lineHeight:1.5,fontSize:12}}/></div>
        <div style={{display:"flex",gap:8}}><button onClick={()=>setShowEmail(false)} style={{...BS,flex:1}}>Cancel</button><button onClick={sendTimesheet} disabled={sending} style={{...BP,flex:1,background:B.purple,opacity:sending?.6:1}}>{sending?"Sending...":"📧 Send"}</button></div>
      </div>
    </Modal>}
  </div>);
}

export { BillingExport };
